# Generated by Django 5.2.15 on 2026-07-01 10:45

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('households', '0002_householdmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_on', models.DateField()),
                ('expiry_date', models.DateField()),
                ('qty', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('unit', models.CharField(choices=[('g', 'G'), ('kg', 'Kg'), ('l', 'L'), ('ml', 'Ml'), ('pieces', 'Pc')], default='pieces', max_length=10)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='households.household')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='catalog.catalog')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('household', 'item'), name='uniq_inventory_household_item')],
            },
        ),
    ]
