# Generated by Django 5.2.15 on 2026-07-01 11:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('households', '0002_householdmember'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inventory',
            name='uniq_inventory_household_item',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.UniqueConstraint(fields=('household', 'item', 'expiry_date', 'purchased_on'), name='uniq_inventory_household_item'),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.CheckConstraint(condition=models.Q(('qty__gt', 0)), name='check_inventory_qty_gt_0'),
        ),
    ]
