# Generated by Django 5.2.15 on 2026-06-29 20:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('households', '0002_householdmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=120)),
                ('item_type', models.CharField(choices=[('frozen', 'Frozen'), ('dairy', 'Dairy'), ('pulses', 'Pulses'), ('miscellaneous', 'Miscellaneous')], default='miscellaneous', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_items', to='households.household')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('item_name', 'household'), name='uniq_household_item')],
            },
        ),
    ]
