# Generated by Django 5.2.15 on 2026-07-19 08:36

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('households', '0002_householdmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unit', models.CharField(choices=[('g', 'G'), ('kg', 'Kg'), ('l', 'L'), ('ml', 'Ml'), ('pieces', 'Pc')], default='pieces', max_length=10)),
                ('qty_needed', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('is_bought', models.BooleanField()),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='households.household')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='catalog.catalog')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('household', 'item'), name='uniq_cart_household_item'), models.CheckConstraint(condition=models.Q(('qty_needed__gt', 0)), name='check_cart_qty_gt_0')],
            },
        ),
    ]
